# Project Manager: Nicholas Howland
# Description:
#   Backup all public GitHub repositories for a specified user
#   using the unauthenticated GitHub API and git mirror clones.
#
#   The entirety of this script was generated by ChatGPT
# 
# License: MIT

#!/usr/bin/env bash
set -euo pipefail

USER="${1:-}"
BACKUP_DIR="${2:-github-backups}"

if [[ -z "$USER" ]]; then
  echo "Usage: $0 <github_username> [backup_dir]"
  exit 1
fi

command -v git >/dev/null || { echo "git is required"; exit 1; }
command -v curl >/dev/null || { echo "curl is required"; exit 1; }
command -v jq >/dev/null || { echo "jq is required"; exit 1; }

mkdir -p "$BACKUP_DIR/$USER"
cd "$BACKUP_DIR/$USER"

page=1

while true; do
  echo "[*] Fetching page $page..."

  repos=$(curl -fsSL \
    "https://api.github.com/users/$USER/repos?per_page=100&page=$page&type=owner&sort=full_name")

  count=$(echo "$repos" | jq 'length')
  [[ "$count" -eq 0 ]] && break

  echo "$repos" | jq -r '.[] | [.name, .clone_url] | @tsv' |
  while IFS=$'\t' read -r name clone_url; do
    target="${name}.git"

    if [[ -d "$target" ]]; then
      echo "[*] Updating $name"
      git -C "$target" remote update --prune
    else
      echo "[*] Cloning $name"
      git clone --mirror "$clone_url" "$target"
    fi
  done

  page=$((page + 1))
done

echo "[+] Backup complete: $BACKUP_DIR/$USER"
